apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-outofsync.slack: test
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
#    targetRevision: "*.*.*"
    targetRevision: 15.5.0
    chart: nginx
    helm:
      releaseName: nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
